Update Designators.xml
Ludeon/RimWorld-fr pull request #413
Opened 2022-10-28 19:48 UTC by Joedox

"Désigne" ou lieu de "Désignez" dans *Desc et pour rester cohérant avec les autres traductions du menu.
Même chose pour "Enleve" et "Enlevez"

L'espace après "Peinture " et "Couleur copiée " est volontaire car il est suivi ": NomDeLaCouleur"

J'ai remplacé "Saisir" par "Copier" car on utilise la pipette dans le jeu pour dupliquer la couleur de l'élément choisi.

"Tinctoria" j'ai mis le T en majuscule car dans la description de la plante celle-ci est présente.

2022-10-28 20:25 UTC, boundir requested changes

2022-10-28 20:25 UTC, boundir commented on Core/Keyed/Designators.xml
> +  <DesignatorPaintBuildingDesc>Désigne les murs et les bâtiments à peindre en utilisant le colorant des plantes Tinctoria, que vous pouvez cultiver. Seuls certains bâtiments peuvent être peints.</Des
Tu garderais pas structure ici ? Il me semble que les statuts peuvent être peintes aussi. Auquel cas bâtiment ou mur ne colle pas.

2022-10-28 20:25 UTC, boundir commented on Core/Keyed/Designators.xml
> +  <DesignatorRemovePaintDesc>Enleve la peinture des murs, batiments et sols.</DesignatorRemovePaintDesc>
Je verrai plus `Retire`. Mais si on garde `Enlève` je veux bien que tu ajoutes l'accent 👀

2022-10-28 20:25 UTC, boundir commented on Core/Keyed/Designators.xml
> +  <SelectAPaintedBuilding>Sélectionnez un élément avec une couleur de peinture.</SelectAPaintedBuilding>
Infinitif ?
Attention à la longueur du texte selon l'emplacement dans le jeu. Description on peut se lâcher mais dans les menus on est plus restreints.

2022-10-28 20:35 UTC, Joedox commented on Core/Keyed/Designators.xml
> +  <DesignatorPaintBuildingDesc>Désigne les murs et les bâtiments à peindre en utilisant le colorant des plantes Tinctoria, que vous pouvez cultiver. Seuls certains bâtiments peuvent être peints.</Des
Effectivement, se serait mieux avec structure.

Par contre modifier une PR tu fais comment ?

2022-10-28 20:36 UTC, boundir commented on Core/Keyed/Designators.xml
> +  <DesignatorPaintBuildingDesc>Désigne les murs et les bâtiments à peindre en utilisant le colorant des plantes Tinctoria, que vous pouvez cultiver. Seuls certains bâtiments peuvent être peints.</Des
Sur ta branche patch-12 tu fais un nouveau commit. Ça mettra à jour la PR

2022-10-28 20:38 UTC, Joedox commented on Core/Keyed/Designators.xml
> +  <DesignatorRemovePaintDesc>Enleve la peinture des murs, batiments et sols.</DesignatorRemovePaintDesc>
Comme tu veux les deux me vont. Et avec l'accent, oui c'est mieux.

2022-10-28 20:42 UTC, Joedox commented on Core/Keyed/Designators.xml
> +  <SelectAPaintedBuilding>Sélectionnez un élément avec une couleur de peinture.</SelectAPaintedBuilding>
Cette phrase se trouve dans un menu flottant.

https://i.imgur.com/7fgChWU.jpg

2022-10-29 11:44 UTC, kiliak commented on Core/Keyed/Designators.xml
> +  <DesignatorRemovePaintDesc>Enleve la peinture des murs, batiments et sols.</DesignatorRemovePaintDesc>
Plutôt retire pour moi également

2022-10-29 11:50 UTC, Joedox commented on Core/Keyed/Designators.xml
> +  <DesignatorRemovePaintDesc>Enleve la peinture des murs, batiments et sols.</DesignatorRemovePaintDesc>
Voir même "décaper"

2022-11-06 09:36 UTC, closed without merging