Ajouts de traductions pour le ripscanner
Ludeon/RimWorld-fr pull request #480
Opened 2024-01-07 14:59 UTC by lp33720

Ajout des messages de mort pour les colons et prisonniers morts du ripscanner.

Ajout de traduction pour `Offset from mechanitor`

Ajout de traduction pour `Patrolling`

2024-02-23 14:20 UTC, boundir requested changes

2024-02-23 14:20 UTC, boundir commented on .vs/ProjectSettings.json
Fichier à retirer du commit

2024-02-23 14:20 UTC, boundir commented on .vs/RimWorld-fr/v16/.suo
Fichier à retirer du commit

2024-02-23 14:20 UTC, boundir commented on .vs/slnx.sqlite
Fichier à retirer du commit

2024-02-23 14:20 UTC, boundir commented on Core/Keyed/FloatMenu.xml
Fichier à retirer du commit car sans modification si ce n'est l'encodage de l'éditeur sans doute ?

2024-02-23 14:20 UTC, boundir commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
> +  <KnowGuestExecuted.stages.someone_was_ripscanned.description>Un prisonnier est mort dans l'extrudeur de sous-noyau. Son cerveau a été brulé pour nourrir la machine.</KnowGuestExecuted.stages.someon
Il manque "C'est horrible." de la version d'origine

2024-02-23 14:20 UTC, boundir commented on Ideology/DefInjected/ThoughtDef/Precepts_PrisonerExecution.xml
> +  <ExecutedColonist_Know_Abhorrent_Mood.stages.colonist_ripscanned.label>Colon scanné par l'extrudeur de sous-noyau</ExecutedColonist_Know_Abhorrent_Mood.stages.colonist_ripscanned.label>
Majuscule à retirer

2024-02-23 14:20 UTC, boundir commented on Ideology/DefInjected/ThoughtDef/Precepts_PrisonerExecution.xml
> +  <ExecutedColonist_Know_Abhorrent_Mood.stages.colonist_ripscanned.description>Un colon est mort dans l'extrudeur de sous-noyau. Son cerveau a été brulé pour nourrir la machine.</ExecutedColonist_Kno
La traduction pour "It's horrifying." est manquante

2024-02-23 14:20 UTC, boundir commented on Ideology/DefInjected/ThoughtDef/Precepts_PrisonerExecution.xml
> +  <ExecutedGuest_Know_Abhorrent_Mood.stages.someone_was_ripscanned.label>Quelqu'un a été scanné par l'extrudeur de sous-noyau</ExecutedGuest_Know_Abhorrent_Mood.stages.someone_was_ripscanned.label>
Majuscule à retirer

2024-02-23 14:20 UTC, boundir commented on Ideology/DefInjected/ThoughtDef/Precepts_PrisonerExecution.xml
> +  <ExecutedGuest_Know_Abhorrent_Mood.stages.someone_was_ripscanned.description>Un colon est mort dans l'extrudeur de sous-noyau. Son cerveau a été brulé pour nourrir la machine.</ExecutedGuest_Know_A
La traduction pour "It's horrifying." est manquante

2024-02-23 14:20 UTC, boundir commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
> +  <KnowColonistExecuted.stages.colonist_ripscanned.label>Colon scanné par l'extrudeur de sous-noyau</KnowColonistExecuted.stages.colonist_ripscanned.label>
Majuscule à retirer

2024-02-23 14:20 UTC, boundir commented on Core/DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
> +  <KnowGuestExecuted.stages.someone_was_ripscanned.label>Quelqu'un a été scanné par l'extrudeur de sous-noyau</KnowGuestExecuted.stages.someone_was_ripscanned.label>
Majuscule à retirer

2024-02-23 16:03 UTC, b606 commented on .vs/slnx.sqlite
C'est un paramétrage de .gitignore

2025-07-15 03:02 UTC, BlastCom commented
Trop ancien et pas de retour de l'auteur sur les commentaires

2025-07-15 03:02 UTC, closed without merging